#include "core/types/class.h"

#include "core/base/class_manager.h"
#include "core/types/box.h"
#include "graphics/forwarding.h"

namespace ark {

namespace {

class DefaultClassImpl final : public IClass {
public:
    Box cast(const Box& box, TypeId id) override {
        if(box.typeId() == id)
            return box;
        return Box();
    }
};

}

Class::Class()
    : _id(0), _name(nullptr), _delegate(nullptr)
{
}

Class::Class(TypeId id)
    : _id(id), _name("<Unknown>"), _delegate(new DefaultClassImpl())
{
}

Class::Class(TypeId id, const char* name, std::unique_ptr<IClass> delegate)
    : _id(id), _name(name), _implements{id}, _delegate(std::move(delegate))
{
}

TypeId Class::id() const
{
    return _id;
}

const char* Class::name() const
{
    return _name;
}

const std::set<TypeId>& Class::implements() const
{
    return _implements;
}

bool Class::is(TypeId id) const
{
    return _id == id;
}

bool Class::isInstance(TypeId id) const
{
    return id == _id || _implements.find(id) != _implements.end();
}

bool Class::isAutoGenerated() const
{
    return _implements.empty();
}

Box Class::cast(const Box& box, TypeId id) const
{
    return _delegate->cast(box, id);
}

void Class::setImplementation(std::set<TypeId> implementation)
{
    _implements = std::move(implementation);
}

Class* Class::ensureClass(TypeId id)
{
    return ClassManager::instance().ensureClass(id);
}

Class* Class::addClass(TypeId id, const char* name, std::unique_ptr<IClass> impl)
{
    return ClassManager::instance().addClass(id, name, std::move(impl));
}

}
