"""

This module only servers as a mimic of the Ark runtime library.
Functionalities are limited or unimplemented.

Use it for:
1. Autocomplete
2. Documentation
3. Unit test(maybe)

"""
from collections.abc import Callable, Sequence, Iterable
from typing import TypeVar, Union, Optional, Tuple, Any, Self


TYPE_INTEGER = Union[int, "Integer"]
TYPE_BOOLEAN = Union[bool, "Boolean"]
TYPE_ENUM = Union[int, 'Enum']
TYPE_INT_OR_FLOAT = Union[int, float]
TYPE_NUMERIC = Union[TYPE_INT_OR_FLOAT, "Numeric"]
TYPE_RECT = tuple[TYPE_INT_OR_FLOAT, TYPE_INT_OR_FLOAT, TYPE_INT_OR_FLOAT, TYPE_INT_OR_FLOAT]
TYPE_VEC2 = Union[tuple[TYPE_NUMERIC, TYPE_NUMERIC], "Vec2"]
TYPE_VEC3 = Union[tuple[TYPE_NUMERIC, TYPE_NUMERIC, TYPE_NUMERIC], "Vec3"]
TYPE_VEC4 = Union[tuple[TYPE_NUMERIC, TYPE_NUMERIC, TYPE_NUMERIC, TYPE_NUMERIC], "Vec4"]
TYPE_INT2 = tuple[int, int]
TYPE_INT3 = tuple[int, int, int]
TYPE_INT4 = tuple[int, int, int, int]
TYPE_FLOAT2 = tuple[float, float]
TYPE_FLOAT3 = tuple[float, float, float]
TYPE_FLOAT4 = tuple[float, float, float, float]
TYPE_M4 = tuple[TYPE_FLOAT4, TYPE_FLOAT4, TYPE_FLOAT4, TYPE_FLOAT4]
TYPE_MAT4 = Union["Mat4", TYPE_M4]
TYPE_NAMED_HASH = Union[TYPE_INTEGER, str, "NamedHash"]
TYPE_RUNNABLE = Union["Runnable", Callable[[], None]]
TYPE_STRING = Union[str, "String"]
TYPE_TYPE_ID = Union[int, str, type]


T = TypeVar('T')


def logd(*args): ...
def logw(*args): ...
def loge(*args): ...
def set_trace_flag(): ...
def load_asset(filename) -> str: ...
def open_asset(filename: str): ...
def load_asset_bundle(filepath: str) -> Optional["AssetBundle"]: ...
def facade() -> "ApplicationFacade": ...
def hash_id(obj: Any) -> int: ...
def build_type() -> int: ...
def is_ark_type(cls: type) -> bool: ...


class Enum:
    BUILD_TYPE_UNDEFINED = 0
    BUILD_TYPE_DEBUG = 1
    BUILD_TYPE_RELEASE = 2
    BUILD_TYPE_RELEASE_WITH_DEBUG_INFO = 3
    BUILD_TYPE_PUBLISHED = 100

    DRAW_MODE_NONE = -1
    DRAW_MODE_LINES = 0
    DRAW_MODE_POINTS = 1
    DRAW_MODE_TRIANGLES = 2
    DRAW_MODE_TRIANGLE_STRIP = 3
    DRAW_MODE_COUNT = 4

    DRAW_PROCEDURE_AUTO = 0
    DRAW_PROCEDURE_DRAW_ARRAYS = 1
    DRAW_PROCEDURE_DRAW_ELEMENTS = 2
    DRAW_PROCEDURE_DRAW_INSTANCED = 3
    DRAW_PROCEDURE_DRAW_INSTANCED_INDIRECT = 4

    UPLOAD_STRATEGY_ONCE = 0
    UPLOAD_STRATEGY_RELOAD = 1
    UPLOAD_STRATEGY_ON_SURFACE_READY = 2
    UPLOAD_STRATEGY_ON_CHANGE = 4
    UPLOAD_STRATEGY_ON_EVERY_FRAME = 8

    UPLOAD_PRIORITY_LOW = 0
    UPLOAD_PRIORITY_NORMAL = 1
    UPLOAD_PRIORITY_HIGH = 2

    INSERT_POSITION_BACK = 0
    INSERT_POSITION_FRONT = 1

    COORDINATE_SYSTEM_DEFAULT = 0
    COORDINATE_SYSTEM_LHS = 1
    COORDINATE_SYSTEM_RHS = 2

    def __init__(self, value: int): ...
    def __int__(self) -> int: ...


class NamedHash(Integer):
    def __init__(self, value: TYPE_NAMED_HASH): ...

    @property
    def hash_code(self) -> int: ...

    @property
    def name(self) -> str: ...

    @staticmethod
    def reverse(hash: int) -> str: ...

    def __index__(self) -> int: ...


class Readable: ...


class Runnable:
    def __init__(self, delegate: TYPE_RUNNABLE): ...
    def __call__(self): ...
    def defer(self, delay: float = 0, canceled: TYPE_BOOLEAN | None = None) -> Self: ...


class Writable: ...


class ModelLoader:
    def load_model(self, resid: int) -> Optional[Model]: ...

    @staticmethod
    def quad(atlas: Atlas) -> ModelLoader: ...


class Asset:
    @property
    def location(self) -> str: ...

    def read_string(self) -> str: ...


class AssetBundle:
    def get_asset(self, path: str) -> Asset: ...
    def get_bundle(self, path: str) -> AssetBundle: ...
    def list_assets(self) -> list[str]: ...


class SearchingNodeProvider:
    def on_visit_adjacent_nodes(self, node_id: TYPE_INT3, position: TYPE_FLOAT3, visitor: Callable[[TYPE_INT3, TYPE_FLOAT3, bool, float], None]): ...


class _Array:
    @property
    def native_ptr(self) -> int: ...

    def wrap(self): ...
    def reset(self, other): ...
    def to_bytes(self) -> bytes: ...
    def to_byte_array(self) -> "ByteArray": ...
    def derivative_2d(self, width: int, height: int) -> "FloatArray": ...
    def integral_2d(self, width: int, height: int) -> "FloatArray": ...
    def convolve_2d(self, width: int, height: int, kernel: "Mat3") -> "FloatArray": ...
    def __len__(self) -> int: ...
    def __getitem__(self, item): ...
    def __setitem__(self, item, value): ...

    @staticmethod
    def zip(components: list["_Array"]) -> "_Array": ...


class IntArray(_Array):
    def __init__(self, size: int, fill: int = 0): ...


class FloatArray(_Array):
    def __init__(self, size: int, fill: int = 0): ...


class ByteArray(_Array):
    def __init__(self, size: int, fill: int = 0): ...
    def to_integer(self) -> "Integer": ...
    def to_numeric(self) -> "Numeric": ...
    def to_vec2(self) -> "Vec2": ...
    def to_vec3(self) -> "Vec3": ...
    def to_vec4(self) -> "Vec4": ...
    def to_mat2(self) -> "Mat2": ...
    def to_mat3(self) -> "Mat3": ...
    def to_mat4(self) -> "Mat4": ...
    def to_float_array(self) -> "FloatArray": ...
    def __getitem__(self, item: slice) -> Self: ...


class _Var:
    @property
    def val(self): ...

    @val.setter
    def val(self, v): ...

    @property
    def delegate(self): ...

    @delegate.setter
    def delegate(self, v): ...

    def reset(self, v=None): ...
    def freeze(self): ...
    def update(self): ...
    def wrap(self): ...
    def clamp(self, a, b): ...
    def floor(self, mod=None): ...
    def ceil(self, mod=None): ...
    def round(self): ...
    def distance(self, other) -> "Numeric": ...
    def distance2(self, other) -> "Numeric": ...
    def if_else(self, condition, otherwise): ...
    def wrap_dirty_callback(self, callback: Runnable) -> Self: ...
    def __int__(self) -> int: ...
    def __mod__(self, other): ...
    def __gt__(self, other) -> "Boolean": ...
    def __ge__(self, other) -> "Boolean": ...
    def __lt__(self, other) -> "Boolean": ...
    def __le__(self, other) -> "Boolean": ...
    def __eq__(self, other) -> "Boolean": ...
    def __ne__(self, other) -> "Boolean": ...
    def __float__(self) -> float: ...
    def __neg__(self): ...


class _Boolean(_Var):
    def negate(self) -> "Boolean": ...
    def expect(self, expectation: TYPE_BOOLEAN, future: "Future") -> "Boolean": ...
    def __or__(self, other) -> "Boolean": ...
    def __and__(self, other) -> "Boolean": ...
    def __bool__(self): ...


class Boolean(_Boolean):
    def __init__(self, value: TYPE_BOOLEAN): ...


class Reflection:
    def __init__(self, delegate: Any): ...
    def __getitem__(self, name: str) -> Runnable: ...
    def create_runnable(self, name: str) -> Optional[Runnable]: ...
    def create_collision_callback(self, on_begin_contact: str = 'on_begin_contact', on_end_contact: str = 'on_end_contact') -> "CollisionCallback": ...
    def create_event_listener(self, on_event: str = 'on_event') -> "EventListener": ...
    def create_searching_node_provider(self, on_visit_adjacent_nodes: str = "on_visit_adjacent_nodes") -> "SearchingNodeProvider": ...
    def create_application_event_listener(self, on_pause: str = "on_pause", on_resume: str = "on_resume", on_unhandled_event: str = "on_unhandled_event") -> "ApplicationEventListener": ...


class Tags:
    def __init__(self, tag: Any = None, tags: Sequence[Any] = tuple()): ...

    @property
    def tag(self) -> Any: ...

    def __getitem__(self, key: TYPE_TYPE_ID) -> Any: ...
    def __setitem__(self, key: TYPE_TYPE_ID, value: Any): ...
    def __delitem__(self, key: TYPE_TYPE_ID): ...


class Json:
    def __init__(self): ...
    def dump(self) -> str: ...
    def to_bson(self) -> ByteArray: ...

    @staticmethod
    def from_bson(content: bytes | ByteArray) -> 'Json': ...


class DOMDocument:
    def __init__(self, name: str, value: str = '', type_: int = 0): ...

    @property
    def name(self) -> str: ...

    @property
    def type(self) -> int: ...

    @property
    def attributes(self) -> list: ...

    @property
    def children(self) -> list['DOMDocument']: ...

    def get_attribute(self, name: str): ...
    def get_child(self, name: str) -> 'DOMDocument': ...
    def ensure_child(self, name: str) -> 'DOMDocument': ...
    def add_child(self, doc: 'DOMDocument'): ...


class Manifest:
    def __init__(self, src: str, descriptor: Optional[DOMDocument] = None): ...

    @property
    def src(self) -> str: ...


class IDHeap:
    def __init__(self, heap_size: int): ...
    def allocate(self, size: int, alignment: int = 1) -> int: ...
    def free(self, ptr: int): ...


class MessageLoop:
    def post(self, task: Callable[[], None], delay: float): ...
    def schedule(self, task: Callable[[], None], interval: float): ...


class Storage:
    def load(self, readable: Readable): ...
    def save(self, writable: Writable): ...
    def json_load(self, json: Json): ...
    def json_dump(self) -> Json: ...


class ApplicationBundle:
    def load_document(self, resid: str) -> DOMDocument: ...
    def load_json(self, resid: str) -> Json: ...
    def load_string(self, resid: str) -> str: ...
    def load_bitmap(self, resid: str) -> "Bitmap": ...


class Future(Runnable):
    def __init__(self, observer: Optional[TYPE_RUNNABLE] = None, canceled: Optional[Boolean] = None, count_down: int = 1): ...

    @property
    def reply(self) -> Any: ...

    @property
    def is_canceled(self) -> Boolean: ...

    @property
    def is_done(self) -> Boolean: ...

    @property
    def is_done_or_canceled(self) -> Boolean: ...

    @property
    def observer(self) -> Optional[Runnable]: ...

    @observer.setter
    def observer(self, observer: TYPE_RUNNABLE): ...

    def cancel(self): ...
    def notify(self, reply: Any = None): ...


class Ref:
    def __init__(self, refid: int): ...
    def __index__(self): ...

    @property
    def id(self) -> int: ...

    @property
    def discarded(self) -> Optional[Boolean]: ...

    @discarded.setter
    def discarded(self, discarded: Boolean): ...

    def discard(self): ...
    def to_entity(self) -> "Entity": ...


class Buffer:
    USAGE_BIT_VERTEX = 1
    USAGE_BIT_INDEX = 2
    USAGE_BIT_DRAW_INDIRECT = 4
    USAGE_BIT_STORAGE = 8
    USAGE_BIT_DYNAMIC = 16
    USAGE_BIT_TRANSFER_SRC = 32
    USAGE_BIT_HOST_VISIBLE = 64

    def __init__(self, usage_bits: int, uploader: "Uploader"): ...

    @property
    def size(self) -> int: ...

    @property
    def id(self) -> int: ...

    def upload(self, uploader: "Uploader", future: Optional[Future] = None): ...
    def synchronize(self, offset: int, size: int, cancelled: "Boolean") -> ByteArray: ...


class Texture:
    FORMAT_AUTO = 0x8000
    FORMAT_R = 0
    FORMAT_RG = 1
    FORMAT_RGB = 2
    FORMAT_RGBA = 3
    FORMAT_SIGNED = 8
    FORMAT_NORMALIZED = 16
    FORMAT_INTEGER = 32
    FORMAT_FLOAT = 64
    FORMAT_8_BIT = 128
    FORMAT_16_BIT = 256
    FORMAT_32_BIT = FORMAT_8_BIT | FORMAT_16_BIT

    USAGE_AUTO = 0
    USAGE_DEPTH_ATTACHMENT = 1
    USAGE_STENCIL_ATTACHMENT = 2
    USAGE_DEPTH_STENCIL_ATTACHMENT = 3
    USAGE_COLOR_ATTACHMENT = 4
    USAGE_ATTACHMENT = USAGE_DEPTH_STENCIL_ATTACHMENT | USAGE_COLOR_ATTACHMENT
    USAGE_SAMPLER = 8
    USAGE_GRAPHICS_STORAGE = 16
    USAGE_COMPUTE_STORAGE = 32
    USAGE_STORAGE = USAGE_GRAPHICS_STORAGE | USAGE_COMPUTE_STORAGE

    FILTER_NEAREST = 0,
    FILTER_LINEAR = 1,
    FILTER_CLAMP_TO_EDGE = 2
    FILTER_CLAMP_TO_BORDER = 3
    FILTER_MIRRORED_REPEAT = 4
    FILTER_REPEAT = 5
    FILTER_MIRROR_CLAMP_TO_EDGE = 6

    def __init__(self, bitmap: "Bitmap", format: int = FORMAT_AUTO, usages: int = USAGE_AUTO, min_filter: int = 1, mag_filter: int = 1, upload_strategy: int = Enum.UPLOAD_STRATEGY_ONCE | Enum.UPLOAD_STRATEGY_ON_SURFACE_READY, future: Optional[Future] = None): ...

    @property
    def format(self) -> int: ...

    @property
    def width(self) -> int: ...

    @property
    def height(self) -> int: ...

    @property
    def depth(self) -> int: ...

    @property
    def size(self) -> "Size": ...

    def reset(self, texture: "Texture"): ...


class RenderController:
    def upload_buffer(self, buffer: Buffer, uploader: "Uploader", upload_strategy: int, future: Optional[Future] = None,
                      upload_priority: int = Enum.UPLOAD_PRIORITY_NORMAL): ...

    def make_buffer(self, buffer_type: int, buffer_usage: int, uploader: Optional["Uploader"], upload_strategy: int, future: Optional[Future] = None) -> Buffer: ...
    def make_vertex_buffer(self, buffer_usage: int = Buffer.USAGE_BIT_DYNAMIC, uploader: Optional["Uploader"] = None) -> Buffer: ...
    def make_index_buffer(self, buffer_usage: int = Buffer.USAGE_BIT_DYNAMIC, uploader: Optional["Uploader"] = None) -> Buffer: ...
    def create_texture2d(self, bitmap: 'Bitmap', texture_format: int = Texture.FORMAT_AUTO, upload_strategy: int = Enum.UPLOAD_STRATEGY_ONCE | Enum.UPLOAD_STRATEGY_ON_SURFACE_READY,
                         future: Optional[Future] = None) -> Texture: ...


class ApplicationFacade:
    def __init__(self): ...

    @property
    def tick(self) -> "Integer": ...

    @property
    def clock(self) -> "Clock": ...

    @property
    def clock_interval(self) -> "Numeric": ...

    @property
    def cursor_position(self) -> "Vec2": ...

    @property
    def surface_size(self) -> "Size": ...

    @property
    def application_controller(self) -> "ApplicationController": ...

    @property
    def application_bundle(self) -> ApplicationBundle: ...

    @property
    def surface_controller(self) -> "SurfaceController": ...

    @property
    def render_controller(self) -> RenderController: ...

    @property
    def camera(self) -> "Camera": ...

    @property
    def manifest(self) -> "ApplicationManifest": ...

    @property
    def resource_loader(self) -> "ResourceLoader": ...

    @property
    def activity(self) -> "Activity": ...

    @activity.setter
    def activity(self, activity: "Activity"): ...

    @property
    def application_event_listener(self) -> Optional["ApplicationEventListener"]: ...

    @application_event_listener.setter
    def application_event_listener(self, application_event_listener: Optional["ApplicationEventListener"]): ...

    @property
    def argv(self) -> list[str]: ...

    def get_asset_bundle(self, path: str) -> AssetBundle: ...
    def get_asset(self, path: str) -> Asset: ...
    def push_clock(self, time_scale: Optional[TYPE_NUMERIC] = None): ...
    def pop_clock(self) -> "Clock": ...
    def to_frag_coord(self, xy: "Vec2", resolution: Optional["Size"] = None) -> "Vec2": ...
    def to_core_runnable(self, runnable: TYPE_RUNNABLE) -> Runnable: ...
    def add_string_bundle(self, name: str, string_bundle: 'StringBundle'): ...
    def create_resource_loader(self, name: str, **kwargs) -> 'ResourceLoader': ...
    def make_message_loop(self, clock: 'Clock') -> MessageLoop: ...
    def add_pre_render_task(self, task: Callable, expired: "Boolean" = None): ...
    def add_control_layer(self, control: Union['Layer', "Renderer"]): ...
    def add_event_listener(self, event_listener: Callable[["Event"], bool], discarded: Optional["Boolean"] = None): ...
    def push_event_listener(self, event_listener: Callable[["Event"], bool], discarded: Optional["Boolean"] = None): ...
    def set_default_event_listener(self, event_listener: Callable[["Event"], bool]): ...
    def get_string(self, resid: str, def_value: Optional[str] = None) -> str: ...
    def get_string_array(self, resid: str) -> list[str]: ...
    def quit(self): ...
    def post(self, task: Optional[Callable], delay: float | list[float], canceled: Optional["Boolean"] = None) -> Future: ...
    def schedule(self, task: Optional[Callable], interval: float, canceled: Optional["Boolean"] = None, count_down: int = 0) -> Future: ...
    def expect(self, condition: Boolean, future: Future): ...
    def screenshot(self, future: Future): ...


class ApplicationController:
    SYSTEM_CURSOR_ARROW = 0
    SYSTEM_CURSOR_IBEAM = 1
    SYSTEM_CURSOR_WAIT = 2
    SYSTEM_CURSOR_CROSSHAIR = 3
    SYSTEM_CURSOR_WAITARROW = 4
    SYSTEM_CURSOR_SIZENWSE = 5
    SYSTEM_CURSOR_SIZENESW = 6
    SYSTEM_CURSOR_SIZEWE = 7
    SYSTEM_CURSOR_SIZENS = 8
    SYSTEM_CURSOR_SIZEALL = 9
    SYSTEM_CURSOR_NO = 10
    SYSTEM_CURSOR_HAND = 11

    def create_cursor(self, bitmap: 'Bitmap', x: int, y: int): ...
    def create_system_cursor(self, name: int): ...
    def show_cursor(self, cursor: Optional = None): ...
    def hide_cursor(self): ...
    def set_mouse_capture(self, enabled: bool): ...


class AtlasImporter: ...


class Atlas:
    @property
    def texture(self) -> Texture: ...

    def has(self, resid: TYPE_NAMED_HASH) -> bool: ...
    def get_item_uv(self, resid: TYPE_NAMED_HASH) -> TYPE_RECT: ...
    def get_original_size(self, resid: TYPE_NAMED_HASH) -> tuple[float, float]: ...
    def get_pivot(self, resid: TYPE_NAMED_HASH) -> tuple[float, float]: ...
    def add_importer(self, importer: AtlasImporter, readable: Optional[Readable] = None): ...
    def make_bitmap_bundle(self): ...


class BroadPhrase: ...


class AudioPlayer:
    PLAY_OPTION_NONE = 0
    PLAY_OPTION_LOOP = 1

    def play(self, source: Union[str, Readable], future: Optional[Future] = None, options: int = PLAY_OPTION_NONE) -> Future: ...


class Font:
    FONT_STYLE_REGULAR = 0
    FONT_STYLE_BOLD = 1
    FONT_STYLE_ITALIC = 2
    FONT_STYLE_MONOCHROME = 4

    def __init__(self, size: str, style: int = 0): ...

    @property
    def style(self) -> int: ...


class Bitmap:
    def __init__(self, width: int, height: int, row_bytes: int, channels: int, data: Optional[ByteArray]): ...

    @property
    def width(self) -> int: ...

    @property
    def height(self) -> int: ...

    @property
    def channels(self) -> int: ...

    @property
    def pixel_size(self) -> int: ...

    @property
    def component_size(self) -> int: ...

    @property
    def row_bytes(self) -> int: ...

    @property
    def bytes(self) -> bytes: ...

    @property
    def byte_array(self) -> Optional[ByteArray]: ...

    def dump(self, filepath: str): ...


class ApplicationManifest:
    @property
    def name(self) -> str: ...

    @property
    def renderer_resolution(self) -> TYPE_FLOAT2: ...


class Observer(Runnable):
    def __init__(self): ...
    def notify(self): ...
    def add_callback(self, callback: TYPE_RUNNABLE): ...
    def add_future_callback(self, future: Future): ...


class Shader: ...


class Renderer:
    PRIORITY_DEFAULT = 0

    PRIORITY_UI = 16
    PRIORITY_UI_BLEND = 17
    PRIORITY_UI_TEXT = 18
    PRIORITY_RENDER_LAYER = 19
    PRIORITY_CONTROL = 20

    def __init__(self, delegate: Optional["Renderer"] | Sequence["Renderer"] = None): ...
    def add_renderer(self, renderer: "Renderer", discarded: TYPE_BOOLEAN, priorty: int = PRIORITY_DEFAULT): ...
    def reset(self, v: Optional["Renderer"]) -> Optional["Renderer"]: ...
    def wrap(self) -> Self: ...
    def to_render_layer(self) -> "RenderLayer": ...
    def with_visible(self, visible: TYPE_BOOLEAN) -> Self: ...


class RenderPass(Renderer):
    def __init__(self, shader, vertex_buffer: Buffer, index_buffer: Buffer, offset: TYPE_INTEGER, draw_count: TYPE_INTEGER, draw_procedure: TYPE_ENUM, draw_mode: TYPE_ENUM = Enum.DRAW_MODE_TRIANGLES,
                 instance_buffers: tuple[tuple[int, "Uploader"]] = tuple(), indirect_buffer: Optional[Buffer] = None): ...


class RenderTarget(Renderer):
    @property
    def renderer(self) -> Renderer: ...


class ResourceLoader:
    def load(self, cls: type[T], type_id: str, **kwargs) -> T: ...

    @property
    def refs(self): ...

    @property
    def layers(self): ...

    @property
    def render_layers(self): ...

    @property
    def packages(self): ...

    def get_reference(self, name: str): ...


class Camera:
    def __init__(self, coordinate_system: int = 0): ...

    @property
    def coordinate_system(self) -> int: ...

    @property
    def fov(self) -> Optional["Numeric"]: ...

    @property
    def aspect(self) -> Optional["Numeric"]: ...

    @property
    def clip_near(self) -> Optional["Numeric"]: ...

    @property
    def clip_far(self) -> Optional["Numeric"]: ...

    @property
    def position(self) -> Optional["Vec3"]: ...

    @property
    def target(self) -> Optional["Vec3"]: ...

    @property
    def up(self) -> Optional["Vec3"]: ...

    @property
    def view(self) -> "Mat4": ...

    @view.setter
    def view(self, view: "Mat4"): ...

    @property
    def projection(self) -> "Mat4": ...

    @projection.setter
    def projection(self, projection: "Mat4"): ...

    @property
    def vp(self) -> "Mat4": ...

    def ortho(self, left_top: TYPE_VEC2, right_bottom: TYPE_VEC2, clip: TYPE_VEC2): ...
    def frustum(self, left, right, top, bottom, near, far): ...
    def perspective(self, fov, aspect, near, far): ...
    def look_at(self, position: TYPE_VEC3, target: TYPE_VEC3, up: TYPE_VEC3): ...
    def to_world_position(self, screen_position: TYPE_VEC3) -> TYPE_VEC3: ...
    def to_viewport_position(self, position: TYPE_VEC3) -> "Vec3": ...
    def to_frustum_slice_matrix(self, z: float, normalize=False) -> "Mat4": ...
    def to_frustum_slice_center_and_matrix(self, z: float, normalize=False) -> tuple["Vec3", "Mat4"]: ...
    def assign(self, camera: "Camera"): ...


class String:
    def __init__(self, value): ...

    @property
    def val(self) -> str: ...

    def set(self, val: TYPE_STRING): ...
    def if_else(self, condition: "Boolean", negative: TYPE_STRING) -> Self: ...

    @staticmethod
    def format(msg: str, **kwargs) -> "String": ...


class _Scalar(_Var):
    def at_least(self, a1, callback: Optional[Runnable] = None) -> Self: ...
    def at_most(self, a1, callback: Optional[Runnable] = None) -> Self: ...
    def fence(self, a1, callback: Optional[Runnable] = None) -> Self: ...
    def dirty(self) -> Boolean: ...
    def __add__(self, other: TYPE_NUMERIC | TYPE_INTEGER) -> Union["Numeric", "Integer"]: ...
    def __radd__(self, other: TYPE_NUMERIC | TYPE_INTEGER) -> Union["Numeric", "Integer"]: ...
    def __sub__(self, other: TYPE_NUMERIC | TYPE_INTEGER) -> Union["Numeric", "Integer"]: ...
    def __rsub__(self, other: TYPE_NUMERIC | TYPE_INTEGER) -> Union["Numeric", "Integer"]: ...
    def __mul__(self, other: TYPE_NUMERIC | TYPE_INTEGER) -> Union["Numeric", "Integer"]: ...
    def __rmul__(self, other: TYPE_NUMERIC | TYPE_INTEGER) -> Union["Numeric", "Integer"]: ...
    def __truediv__(self, other: TYPE_NUMERIC | TYPE_INTEGER) -> "Numeric": ...
    def __rtruediv__(self, other: TYPE_NUMERIC | TYPE_INTEGER) -> Self: ...
    def __pow__(self, power: TYPE_NUMERIC | TYPE_INTEGER) -> Self: ...
    def __abs__(self) -> Self: ...


class Numeric(_Scalar):
    def __init__(self, val): ...
    def integral(self, t: Optional["Numeric"] = None) -> "Numeric": ...
    def if_else(self, condition: Union[bool, Boolean], negative: Union[float, "Numeric"]) -> Self: ...
    def synchronize(self, discarded: Boolean) -> "Numeric": ...
    def track(self, s0: float, speed: float, distance: float, future: Optional[Future] = None, t: Optional["Numeric"] = None) -> Self: ...
    def sod(self, s0: float, f: float, z: float = 1.0, r: float = 0, t: Optional["Numeric"] = None) -> Self: ...
    def almost_equal(self, other: TYPE_NUMERIC, tolerance: float = 0.0) -> Boolean: ...
    def normalize(self) -> Self: ...
    def lerp(self, b: TYPE_NUMERIC, t: TYPE_NUMERIC) -> Self: ...
    def __floordiv__(self, other): ...


class Integer(_Scalar):
    REPEAT_NONE = 0
    REPEAT_REVERSE = 1
    REPEAT_LOOP = 4
    REPEAT_LAST = 8
    REPEAT_NOTIFY = 16

    def __init__(self, value: Union[TYPE_NAMED_HASH, "Integer", Numeric]): ...

    @staticmethod
    def repeat(array: list[int], repeat: int) -> "Integer": ...

    @staticmethod
    def to_repeat(repeat: str) -> int: ...

    @staticmethod
    def animate(frames: Sequence[int], frame_index: TYPE_INTEGER, future: Future) -> "Integer": ...

    def __len__(self): ...
    def __getitem__(self, index: TYPE_INTEGER) -> "Integer": ...
    def __floordiv__(self, other: TYPE_INTEGER) -> "Integer": ...


class Discarded(Boolean):
    def __init__(self, discarded: TYPE_BOOLEAN = False): ...
    def discard(self): ...
    def observe(self, observer: Observer) -> Boolean: ...


class Vec2i:
    def __init__(self, x: TYPE_INTEGER, y: Optional[TYPE_INTEGER] = None): ...


class Vec3i:
    def __init__(self, x: TYPE_INTEGER, y: Optional[TYPE_INTEGER] = None, z: Optional[TYPE_INTEGER] = None): ...


class Vec4i:
    def __init__(self, x: TYPE_INTEGER, y: Optional[TYPE_INTEGER] = None, z: Optional[TYPE_INTEGER] = None, w: Optional[TYPE_INTEGER] = None): ...


class Vec2(_Var):
    def __init__(self, x: TYPE_NUMERIC, y: Optional[TYPE_NUMERIC] = None): ...

    @property
    def x(self) -> Numeric: ...

    @x.setter
    def x(self, v): ...

    @property
    def y(self) -> Numeric: ...

    @property
    def xy(self) -> "Vec2": ...

    @y.setter
    def y(self, v): ...

    @property
    def delegate(self): ...

    def transform(self, transform): ...
    def integral(self, t: Optional[Numeric] = None) -> Self: ...
    def wrap(self) -> Self: ...
    def synchronize(self, discarded: Optional[Boolean] = None) -> Self: ...
    def attract(self, s0: Union[tuple, "Vec2"], duration: float, t: Optional[Numeric] = None) -> Self: ...
    def fence(self, plane: Union["Vec3", tuple], observer: Union[Observer, Callable[[], None]]) -> Self: ...
    def atan2(self) -> Numeric: ...
    def normalize(self): ...
    def hypot(self) -> Numeric: ...
    def hypot2(self) -> Numeric: ...
    def to_size(self) -> "Size": ...
    def lerp(self, other, t: TYPE_NUMERIC) -> Self: ...
    def track(self, s0, speed: float, distance: float, future: Optional[Future] = None, t: Optional[Numeric] = None) -> Self: ...
    def sod(self, s0, f: float, z: float = 1, r: float = 0, t: Optional[Numeric] = None) -> Self: ...
    def extend(self, v: TYPE_VEC2 | TYPE_NUMERIC): ...
    def __add__(self, other: TYPE_VEC2 | TYPE_VEC3 | TYPE_VEC4) -> Self: ...
    def __sub__(self, other: TYPE_VEC2 | TYPE_VEC3 | TYPE_VEC4) -> Self: ...
    def __mul__(self, other: TYPE_NUMERIC | TYPE_INTEGER | TYPE_VEC2 | TYPE_VEC3 | TYPE_VEC4) -> Self: ...
    def __radd__(self, other: TYPE_VEC2 | TYPE_VEC3 | TYPE_VEC4) -> Self: ...
    def __rsub__(self, other: TYPE_VEC2 | TYPE_VEC3 | TYPE_VEC4) -> Self: ...
    def __rmul__(self, other: TYPE_NUMERIC | TYPE_INTEGER | TYPE_VEC2 | TYPE_VEC3 | TYPE_VEC4) -> Self: ...
    def __truediv__(self, other: TYPE_NUMERIC | TYPE_INTEGER | TYPE_VEC2 | TYPE_VEC3 | TYPE_VEC4) -> Self: ...
    def __iter__(self): ...
    def __len__(self): ...
    def __getitem__(self, i): ...
    def __str__(self): ...


class Vec3(Vec2):
    def __init__(self, x: TYPE_NUMERIC, y: Optional[TYPE_NUMERIC] = None, z: Optional[TYPE_NUMERIC] = None): ...

    @property
    def z(self): ...

    @z.setter
    def z(self, v): ...

    @property
    def xyz(self) -> "Vec3": ...

    @property
    def xz(self) -> Vec2: ...

    @property
    def yx(self) -> Vec2: ...

    @property
    def yz(self) -> Vec2: ...

    @property
    def zx(self) -> Vec2: ...

    @property
    def zy(self) -> Vec2: ...

    def cross(self, other: TYPE_VEC3) -> "Vec3": ...
    def extend(self, w: TYPE_NUMERIC) -> "Vec4": ...


class Vec4(Vec3):
    def __init__(self, x: TYPE_NUMERIC, y: Optional[TYPE_NUMERIC] = None, z: Optional[TYPE_NUMERIC] = None, w: Optional[TYPE_NUMERIC] = None): ...

    @property
    def w(self): ...

    @w.setter
    def w(self, v): ...

    @property
    def xyzw(self) -> tuple[float, float, float, float]: ...

    @property
    def vw(self): ...

    @vw.setter
    def vw(self, v): ...


class _Mat:
    def __mul__(self, other): ...
    def __matmul__(self, other): ...

    @property
    def val(self) -> tuple: ...

    def translate(self, translation: Vec2 | Vec3): ...
    def rotate(self, rot: Union[float, Numeric, 'Rotation']): ...
    def freeze(self): ...
    def if_else(self, condition: Boolean, other): ...

    @staticmethod
    def identity(): ...


class Mat2(_Mat):
    def __init__(self, t=None, b=None): ...


class Mat3(_Mat):
    def __init__(self, t=None, b=None, n=None): ...


class Mat4(_Mat):
    def __init__(self, t=None, b=None, n=None, w=None): ...


class Translation(Vec3):
    def __init__(self, translate: TYPE_VEC3): ...
    def reset(self, position: TYPE_VEC3): ...
    def to_matrix(self) -> Mat4: ...


class Scale(Vec3):
    def __init__(self, scale: TYPE_VEC3): ...
    def reset(self, scale: TYPE_VEC3): ...
    def to_matrix(self) -> Mat4: ...


class Uploader:
    def __init__(self, value: Union[Numeric, Vec2, Vec3, Vec4, list[_Mat], list[tuple], list[int], list["Uploader"], Any] = None): ...

    @property
    def size(self): ...

    def reserve(self, size: int) -> Self: ...
    def repeat(self, length: int, stride: int = 0) -> Self: ...
    def once(self) -> Self: ...
    def wrap(self) -> "Uploader": ...
    def reset(self, value: "Uploader"): ...
    def mark_dirty(self): ...
    def dye(self, condition: TYPE_BOOLEAN = True, message: str = '') -> Self: ...
    def __setitem__(self, offset: int, uploader: "Uploader"): ...
    def __delitem__(self, offset: int): ...


class AnimationInput(Uploader):
    def get_node_matrix(self, node_name: str) -> Mat4: ...
    def get_transform_variance(self, c: tuple[float, float, float], nodes: list[str]) -> list[float]: ...


class Animation:
    @property
    def ticks(self) -> int: ...

    @property
    def tps(self) -> float: ...

    @property
    def duration(self) -> float: ...

    def get_local_transforms(self, t: TYPE_INTEGER | TYPE_NUMERIC) -> list[tuple[str, Mat4]]: ...
    def get_global_transform(self, node: "Node", t: TYPE_INTEGER | TYPE_NUMERIC) -> Mat4: ...


class MaterialMap:
    @property
    def color(self) -> Optional[Vec4]: ...

    @property
    def value(self) -> Optional[Numeric]: ...

    @property
    def bitmap(self) -> Optional[Bitmap]: ...


class Material:
    @property
    def id(self) -> int: ...

    @id.setter
    def id(self, v: int): ...

    @property
    def name(self) -> str: ...

    @property
    def base_color(self) -> Optional[MaterialMap]: ...

    @property
    def normal(self) -> Optional[MaterialMap]: ...

    @property
    def roughness(self) -> Optional[MaterialMap]: ...

    @property
    def metallic(self) -> Optional[MaterialMap]: ...

    @property
    def specular(self) -> Optional[MaterialMap]: ...

    @property
    def emission(self) -> Optional[MaterialMap]: ...


class Mesh:
    @property
    def name(self) -> str: ...

    @property
    def vertex_count(self) -> int: ...

    @property
    def indices(self) -> list[int]: ...

    @property
    def vertices(self) -> list[float]: ...

    @property
    def material(self) -> Optional[Material]: ...


class Node:
    @property
    def name(self) -> str: ...

    @property
    def parent_node(self) -> Optional["Node"]: ...

    @property
    def child_nodes(self) -> list['Node']: ...

    @property
    def meshes(self) -> list[Mesh]: ...

    @property
    def local_matrix(self) -> TYPE_M4: ...

    @property
    def global_matrix(self) -> TYPE_M4: ...

    @property
    def translation(self) -> TYPE_FLOAT3: ...

    @property
    def rotation(self) -> TYPE_FLOAT4: ...

    @property
    def scale(self) -> TYPE_FLOAT3: ...

    @property
    def local_aabb(self) -> tuple[TYPE_FLOAT3, TYPE_FLOAT3]: ...

    def find_child_node(self, name: str) -> Optional['Node']: ...


class Boundaries:
    def __init__(self, aabb_min: Optional[TYPE_VEC3], aabb_max: Optional[TYPE_VEC3], center: Optional[TYPE_VEC3] = None, size: Optional[TYPE_VEC3] = None): ...

    @property
    def aabb_min(self) -> Vec3: ...

    @property
    def aabb_max(self) -> Vec3: ...

    @property
    def size(self) -> Vec3: ...

    @property
    def center(self) -> Vec3: ...

    def freeze(self) -> Self: ...


class Vertices:
    @property
    def length(self) -> int: ...

    def make_uploader(self, shader: Shader, size: TYPE_VEC3) -> Uploader: ...


class Model:
    @property
    def content(self) -> Boundaries: ...

    @property
    def occupy(self) -> Boundaries: ...

    @property
    def materials(self) -> list[Material]: ...

    @property
    def meshes(self) -> list[Mesh]: ...

    @property
    def index_count(self) -> int: ...

    @property
    def vertex_count(self) -> int: ...

    @property
    def animations(self) -> dict[str, Animation]: ...

    @property
    def root_node(self) -> Optional[Node]: ...

    @property
    def indices(self) -> Uploader: ...

    @property
    def vertices(self) -> Vertices: ...

    def find_node(self, name: str) -> Optional[Node]: ...
    def get_animation(self, name: str) -> Animation: ...


class ModelBundle:
    @property
    def index_length(self) -> int: ...

    @property
    def vertex_length(self) -> int: ...

    @property
    def materials(self) -> list[Material]: ...

    @property
    def images(self) -> dict[str, Bitmap]: ...

    @property
    def textures(self) -> list[Texture]: ...

    def get_model(self, t: TYPE_NAMED_HASH) -> Model: ...
    def import_materials(self, manifest: str | Manifest): ...
    def update_materials(self): ...
    def import_model(self, t: TYPE_NAMED_HASH, manifest: str | Manifest, future: Optional[Future] = None) -> Optional[Model]: ...


class LevelLibrary:
    @property
    def id(self) -> int: ...

    @property
    def name(self) -> str: ...

    @property
    def size(self) -> Vec3: ...

    @property
    def shape(self) -> "Shape": ...

    @shape.setter
    def shape(self, shape: "Shape"): ...


class LevelObject:
    TYPE_INSTANCE = 0
    TYPE_MESH = 1
    TYPE_CAMERA = 2
    TYPE_LIGHT = 3

    @property
    def name(self) -> str: ...

    @property
    def type(self) -> int: ...

    @property
    def visible(self) -> bool: ...

    @property
    def position(self) -> TYPE_FLOAT3: ...

    @property
    def scale(self) -> Optional[TYPE_FLOAT3]: ...

    @property
    def shape(self) -> Optional[TYPE_FLOAT3]: ...

    @property
    def rotation(self) -> Optional[TYPE_FLOAT4]: ...

    @property
    def library(self) -> Optional[LevelLibrary]: ...

    @property
    def render_object(self) -> "RenderObject": ...

    @property
    def rigidbody(self) -> "Rigidbody": ...

    def __getitem__(self, key: str) -> Optional[str]: ...
    def create_render_object(self) -> "RenderObject": ...


class LevelLayer:
    @property
    def name(self) -> str: ...

    @property
    def objects(self) -> list[LevelObject]: ...

    def get_object(self, name: str) -> Optional[LevelObject]: ...
    def create_render_objects(self, layer: Optional["Layer"] = None): ...


class Level:
    def __init__(self, src: str): ...

    @property
    def libraries(self) -> dict[int, LevelLibrary]: ...

    @property
    def layers(self) -> list[LevelLayer]: ...

    @property
    def cameras(self) -> dict[str, "Camera"]: ...

    @property
    def lights(self) -> dict[str, "Vec3"]: ...

    def get_layer(self, name: str) -> LevelLayer: ...
    def get_camera(self, name: str) -> Optional[Camera]: ...
    def get_light(self, name: str) -> Optional[Vec3]: ...


class RenderObject:
    def __init__(self, resid: TYPE_NAMED_HASH, position: Optional[TYPE_VEC3] = None, size: Optional[TYPE_VEC3] = None, transform: Optional["Transform"] = None, varyings: Optional["Varyings"] = None, visible: Optional[TYPE_BOOLEAN] = None, discarded: Optional[TYPE_BOOLEAN] = None): ...

    @property
    def type(self) -> Integer: ...

    @type.setter
    def type(self, val): ...

    @property
    def position(self) -> Vec3: ...

    @position.setter
    def position(self, v): ...

    @property
    def discarded(self) -> Boolean: ...

    @discarded.setter
    def discarded(self, discarded: Boolean): ...

    @property
    def tag(self): ...

    @tag.setter
    def tag(self, tag): ...

    @property
    def x(self) -> float: ...

    @property
    def y(self) -> float: ...

    @property
    def z(self) -> float: ...

    @property
    def size(self) -> "Size": ...

    @size.setter
    def size(self, v: "Size"): ...

    @property
    def transform(self) -> 'Transform': ...

    @transform.setter
    def transform(self, transform): ...

    @property
    def varyings(self) -> "Varyings": ...

    @varyings.setter
    def varyings(self, v): ...

    @property
    def visible(self) -> Boolean: ...

    @visible.setter
    def visible(self, val: Union[Boolean, bool]): ...

    @property
    def xy(self) -> Tuple[float, float]: ...

    @property
    def xyz(self) -> Tuple[float, float, float]: ...

    def discard(self): ...
    def show(self): ...
    def hide(self): ...


class LayerContext: ...


class RenderLayer(Renderer):
    def __init__(self, model_loader: ModelLoader, shader: Shader, varyings: Varyings, visible: Boolean | None, discarded: Boolean | None, scissor: Vec4 | None): ...

    @property
    def context(self) -> LayerContext: ...

    @property
    def shader(self) -> Shader: ...

    @property
    def visible(self) -> Boolean: ...

    @visible.setter
    def visible(self, visible: TYPE_BOOLEAN): ...

    def make_layer(self, model_loader: Optional[ModelLoader] = None, position: Optional[Vec3] = None, visible: Optional[Boolean] = None,
                   discarded: Optional[Boolean] = None) -> "Layer": ...


class Layer:
    def __init__(self): ...

    @property
    def model_loader(self) -> ModelLoader: ...

    @property
    def shader(self) -> Shader: ...

    @property
    def position(self) -> Optional[Vec3]: ...

    @position.setter
    def position(self, position: TYPE_VEC3): ...

    @property
    def visible(self) -> Boolean: ...

    @visible.setter
    def visible(self, visible: TYPE_BOOLEAN): ...

    @property
    def discarded(self) -> Boolean: ...

    def add(self, render_object: RenderObject, discarded: Boolean = None, updatable: Any = None): ...
    def clear(self): ...


class Artifact(Uploader):
    def __init__(self, **kwargs): ...
    def make_uploader(self, repeat_count: int, index: Optional[Integer] = None) -> Uploader: ...


class Arena:
    def __init__(self, resource_loader: ResourceLoader, render_layers: dict[str, RenderLayer] = None, layers: dict[str, Layer] = None): ...

    @property
    def layers(self): ...

    @property
    def render_layers(self): ...

    def add_layer(self, name: str, layer: Layer): ...
    def add_render_layer(self, name: str, render_layer: RenderLayer): ...


class Activity(Renderer):
    def __init__(self): ...
    def add_render_layer(self, render_layer: Renderer, discarded: Optional[Boolean] = None): ...
    def add_event_listener(self, event_listener: Union[Callable[["Event"], bool], "EventListener"], disabled: Optional[Boolean] = None): ...


class Clock:
    @property
    def tick(self) -> int: ...

    def duration(self) -> "Numeric": ...
    def timeout(self, seconds: float) -> "Boolean": ...
    def pause(self): ...
    def resume(self): ...


class Event:
    ACTION_NONE = 0
    ACTION_KEY_DOWN = 1
    ACTION_KEY_UP = 2
    ACTION_KEY_REPEAT = 3
    ACTION_DOWN = 4
    ACTION_UP = 5
    ACTION_MOVE = 6
    ACTION_WHEEL = 7
    ACTION_BACK_PRESSED = 8
    ACTION_CANCEL = 9

    CODE_NONE = 0
    CODE_MOUSE_BUTTON_LEFT = 1
    CODE_MOUSE_BUTTON_MIDDLE = 2
    CODE_MOUSE_BUTTON_RIGHT = 3
    CODE_KEYBOARD_A = 1
    CODE_KEYBOARD_B = 2
    CODE_KEYBOARD_C = 3
    CODE_KEYBOARD_D = 4
    CODE_KEYBOARD_E = 5
    CODE_KEYBOARD_F = 6
    CODE_KEYBOARD_G = 7
    CODE_KEYBOARD_H = 8
    CODE_KEYBOARD_I = 9
    CODE_KEYBOARD_J = 10
    CODE_KEYBOARD_K = 11
    CODE_KEYBOARD_L = 12
    CODE_KEYBOARD_M = 13
    CODE_KEYBOARD_N = 14
    CODE_KEYBOARD_O = 15
    CODE_KEYBOARD_P = 16
    CODE_KEYBOARD_Q = 17
    CODE_KEYBOARD_R = 18
    CODE_KEYBOARD_S = 19
    CODE_KEYBOARD_T = 20
    CODE_KEYBOARD_U = 21
    CODE_KEYBOARD_V = 22
    CODE_KEYBOARD_W = 23
    CODE_KEYBOARD_X = 24
    CODE_KEYBOARD_Y = 25
    CODE_KEYBOARD_Z = 26
    CODE_KEYBOARD_0 = ord('0')
    CODE_KEYBOARD_1 = ord('1')
    CODE_KEYBOARD_2 = ord('2')
    CODE_KEYBOARD_3 = ord('3')
    CODE_KEYBOARD_4 = ord('4')
    CODE_KEYBOARD_5 = ord('5')
    CODE_KEYBOARD_6 = ord('6')
    CODE_KEYBOARD_7 = ord('7')
    CODE_KEYBOARD_8 = ord('8')
    CODE_KEYBOARD_9 = ord('9')
    CODE_KEYBOARD_F1 = 27
    CODE_KEYBOARD_F2 = 28
    CODE_KEYBOARD_F3 = 29
    CODE_KEYBOARD_F4 = 30
    CODE_KEYBOARD_F5 = 31
    CODE_KEYBOARD_F6 = 32
    CODE_KEYBOARD_F7 = 33
    CODE_KEYBOARD_F8 = 34
    CODE_KEYBOARD_F9 = 35
    CODE_KEYBOARD_F10 = 36
    CODE_KEYBOARD_F11 = 37
    CODE_KEYBOARD_F12 = 38
    CODE_KEYBOARD_GRAVE = 39
    CODE_KEYBOARD_RIGHT = 40
    CODE_KEYBOARD_LEFT = 41
    CODE_KEYBOARD_DOWN = 42
    CODE_KEYBOARD_UP = 43
    CODE_KEYBOARD_ENTER = 44
    CODE_KEYBOARD_ESCAPE = 45
    CODE_KEYBOARD_BACKSPACE = 46
    CODE_KEYBOARD_TAB = 47
    CODE_KEYBOARD_SPACE = 48

    CODE_KEYBOARD_LSHIFT = 1001
    CODE_KEYBOARD_RSHIFT = 1002
    CODE_KEYBOARD_LCTRL = 1003
    CODE_KEYBOARD_RCTRL = 1004
    CODE_KEYBOARD_LALT = 1005
    CODE_KEYBOARD_RALT = 1006
    CODE_KEYBOARD_INSERT = 1007
    CODE_KEYBOARD_HOME = 1008
    CODE_KEYBOARD_END = 1009
    CODE_KEYBOARD_PAGE_UP = 1010
    CODE_KEYBOARD_PAGE_DOWN = 1011

    CODE_KEYBOARD_BACK = 1012
    CODE_KEYBOARD_MENU = 1013

    KEY_MODIFIER_LSHIFT = 1
    KEY_MODIFIER_RSHIFT = 1 << 1
    KEY_MODIFIER_SHIFT = KEY_MODIFIER_LSHIFT | KEY_MODIFIER_RSHIFT
    KEY_MODIFIER_LCTRL = 1 << 2
    KEY_MODIFIER_RCTRL = 1 << 3
    KEY_MODIFIER_CTRL = KEY_MODIFIER_LCTRL | KEY_MODIFIER_RCTRL
    KEY_MODIFIER_LALT = 1 << 4
    KEY_MODIFIER_RALT = 1 << 5
    KEY_MODIFIER_ALT = KEY_MODIFIER_LALT | KEY_MODIFIER_RALT
    KEY_MODIFIER_LGUI = 1 << 6
    KEY_MODIFIER_RGUI = 1 << 7
    KEY_MODIFIER_GUI = KEY_MODIFIER_LGUI | KEY_MODIFIER_RGUI

    BUTTON_NONE = 0
    BUTTON_MOUSE_LEFT = 1
    BUTTON_MOUSE_MIDDLE = 2
    BUTTON_MOUSE_RIGHT = 3
    BUTTON_MOTION_POINTER1 = 4
    BUTTON_MOTION_POINTER2 = 5
    BUTTON_MOTION_POINTER3 = 6
    BUTTON_MOTION_POINTER4 = 7

    @property
    def action(self) -> int: ...

    @property
    def code(self) -> int: ...

    @property
    def key_modifier(self) -> int: ...

    @property
    def button(self) -> int: ...

    @property
    def x(self) -> int: ...

    @property
    def y(self) -> int: ...

    @property
    def xy(self) -> tuple: ...

    @property
    def timestamp(self) -> int: ...


class Rotation(Vec4):
    def __init__(self, quaternion: TYPE_VEC4): ...
    def reset(self, quaternion: Vec4): ...
    def set_axis_theta(self, axis: TYPE_VEC3, theta: TYPE_NUMERIC): ...
    def set_euler(self, pitch: TYPE_NUMERIC, yaw: TYPE_NUMERIC, roll: TYPE_NUMERIC): ...
    def apply_to(self, v: TYPE_VEC3 | TYPE_VEC4) -> Union[TYPE_VEC3, TYPE_VEC4]: ...
    def to_matrix(self) -> Mat4: ...
    def freeze(self) -> Self: ...
    def __mul__(self, other: "Rotation") -> Self: ...

    @staticmethod
    def axis_theta(axis: TYPE_VEC3, theta: TYPE_NUMERIC) -> "Rotation": ...

    @staticmethod
    def euler_angle(pitch: TYPE_NUMERIC, yaw: TYPE_NUMERIC, roll: TYPE_NUMERIC) -> "Rotation": ...

    @staticmethod
    def vector_reorientation(u: TYPE_VEC3, v: TYPE_VEC3) -> "Rotation": ...


class Transform(Mat4):
    TYPE_NONE = 0
    TYPE_LINEAR_2D = 1
    TYPE_LINEAR_3D = 2

    def __init__(self, matrix: Mat4): ...

    @property
    def rotation(self) -> Vec4: ...

    @rotation.setter
    def rotation(self, rotation: Vec4): ...

    @property
    def scale(self) -> Vec3: ...

    @scale.setter
    def scale(self, v): ...

    @property
    def translation(self) -> Vec3: ...

    @translation.setter
    def translation(self, v): ...


class Transform2D(Transform):
    def __init__(self, rotation: Optional[TYPE_NUMERIC] = None, scale: Optional[TYPE_VEC2] = None, pivot: Optional[TYPE_VEC2] = None): ...


class Transform3D(Transform):
    def __init__(self, rotation: Optional[TYPE_VEC4] = None, scale: Optional[TYPE_VEC3] = None, translation: Optional[TYPE_VEC3] = None): ...


class Random:
    def __init__(self, seed: Optional[int] = None, nonvolatile: bool = True): ...

    @property
    def seed(self): ...

    @seed.setter
    def seed(self, seed): ...

    def rand(self) -> int: ...
    def randint(self, a: int, b: int) -> int: ...
    def uniform(self, a: float, b: float) -> float: ...
    def normal(self, mean: float, sigma: float) -> float: ...
    def rand_integer(self, a: TYPE_INTEGER, b: TYPE_INTEGER) -> Integer: ...
    def rand_numeric(self, a: TYPE_NUMERIC, b: TYPE_NUMERIC) -> Numeric: ...
    def normal_numeric(self, mean: TYPE_NUMERIC, sigma: TYPE_NUMERIC) -> Numeric: ...
    def choice(self, choices: Sequence[int | float], weights: Iterable[float] = ()) -> Integer | Numeric: ...


class Math:
    @staticmethod
    def log2(x): ...

    @staticmethod
    def abs(x): ...

    @staticmethod
    def sin(x): ...

    @staticmethod
    def cos(x): ...

    @staticmethod
    def acos(x): ...

    @staticmethod
    def max(a, b): ...

    @staticmethod
    def min(a, b): ...

    @staticmethod
    def sqrt(x): ...

    @staticmethod
    def hypot(x, y): ...

    @staticmethod
    def hypot2(x, y): ...

    @staticmethod
    def dot(x, y) -> Numeric: ...

    @staticmethod
    def normalize(x): ...

    @staticmethod
    def distance(a, b) -> TYPE_NUMERIC: ...

    @staticmethod
    def distance2(a, b) -> TYPE_NUMERIC: ...

    @staticmethod
    def atan(x): ...

    @staticmethod
    def atan2(dy, dx): ...

    @staticmethod
    def lerp(a, b, t): ...

    @staticmethod
    def tanh(x): ...

    @staticmethod
    def hash(x: Union[int, float, TYPE_FLOAT2, TYPE_FLOAT3, TYPE_FLOAT4]): ...


class Size(Vec3):
    def __init__(self, width: TYPE_NUMERIC, height: TYPE_NUMERIC, depth: Optional[TYPE_NUMERIC] = None): ...

    @property
    def width(self) -> Numeric: ...

    @width.setter
    def width(self, width: TYPE_NUMERIC): ...

    @property
    def height(self) -> Numeric: ...

    @height.setter
    def height(self, height: TYPE_NUMERIC): ...

    @property
    def depth(self) -> Numeric: ...

    @depth.setter
    def depth(self, depth: TYPE_NUMERIC): ...

    def reset(self, other: "Size"): ...


class Tile:
    def __init__(self, id_: int, type_: str = '', shape_id: int = -1, render_object: Optional[RenderObject] = None): ...

    @property
    def id(self) -> int: ...

    @property
    def type(self) -> str: ...

    @type.setter
    def type(self, t: str): ...

    @property
    def shape_id(self) -> int: ...

    @shape_id.setter
    def shape_id(self, shape_id: int): ...

    @property
    def render_object(self) -> Optional[RenderObject]: ...

    @render_object.setter
    def render_object(self, render_object: Optional[RenderObject]): ...


class TilemapImporter: ...


class Tileset:
    def __init__(self, tile_size: Size): ...

    @property
    def tiles(self) -> dict[int, Tile]: ...

    @property
    def tile_width(self) -> float: ...

    @property
    def tile_height(self) -> float: ...

    def add_tile(self, tile: Tile): ...
    def get_tile(self, tile_id: int) -> Optional[Tile]: ...
    def load(self, src: Union[Readable, str]): ...


class TilemapLayer(Renderer):
    def __init__(self, tileset: Tileset, name: str, row_count: int, col_count: int, position: Optional[TYPE_VEC3] = None, visible: Optional[Boolean] = None,
                 collision_filter: Optional['CollisionFilter'] = None): ...

    @property
    def position(self) -> Optional[Vec3]: ...

    @position.setter
    def position(self, position: Optional[TYPE_VEC3]): ...

    @property
    def col_count(self) -> int: ...

    @property
    def row_count(self) -> int: ...

    @property
    def name(self) -> str: ...

    @property
    def flags(self) -> int: ...

    @flags.setter
    def flags(self, flag): ...

    @property
    def tileset(self) -> Tileset: ...

    def get_tile(self, col: int, row: int) -> Optional[Tile]: ...
    def get_tile_rect(self, rect: TYPE_INT4) -> list[int]: ...
    def set_tile(self, col: int, row: int, tile: Union[int, RenderObject, Tile, None]): ...
    def set_tile_rect(self, tiles: list[int], dest: TYPE_INT4): ...
    def foreach_tile(self, callback: Callable[[int, int, Tile], bool]): ...
    def resize(self, col_count: int, row_count: int, offset_x: int = 0, offset_y: int = 0): ...
    def clear(self): ...


class Tilemap:
    LAYER_FLAG_DEFAULT = 0
    LAYER_FLAG_COLLIDABLE = 1
    LAYER_FLAG_SCROLLABLE = 2
    LAYER_FLAG_INVISIBLE = 4

    def __init__(self, tileset: Tileset, render_layer: Optional[RenderLayer] = None): ...

    @property
    def tileset(self) -> Tileset: ...

    @property
    def position(self): ...

    @position.setter
    def position(self, val): ...

    @property
    def layers(self) -> list[TilemapLayer]: ...

    @property
    def storage(self) -> Optional[Storage]: ...

    def clear(self): ...
    def make_layer(self, name: str, col_count: int, row_count: int, position: Optional[TYPE_VEC3] = None, visible: Optional[Boolean] = None,
                   collision_filter: Optional['CollisionFilter'] = None, zorder: float = 0) -> TilemapLayer: ...
    def add_layer(self, layer: TilemapLayer, zorder: float = 0): ...
    def remove_layer(self, layer: TilemapLayer): ...
    def load(self, src: Union[Readable, str]): ...
    def find_route(self, start: tuple[int, int], goal: tuple[int, int]) -> list[tuple[int, int]]: ...


class Function:
    def __init__(self, d): ...


class EventListener:
    def on_event(self, event: Event): ...
    def wrap(self, delegate: "EventListener") -> Self: ...
    def reset(self, event_listener: Any = None): ...


class EventDispatcher(EventListener):
    @property
    def locked(self) -> bool: ...

    @locked.setter
    def locked(self, locked: bool): ...

    def on_event(self, event): ...
    def on_key_event(self, code, on_press: Optional[TYPE_RUNNABLE] = None, on_release: Optional[TYPE_RUNNABLE] = None, on_repeat: Optional[TYPE_RUNNABLE] = None): ...
    def on_motion_event(self, on_press: Optional[EventListener] = None, on_release: Optional[EventListener] = None, on_click: Optional[EventListener] = None, on_move: Optional[EventListener] = None): ...


class Glyph:
    def __init__(self, type: TYPE_INTEGER, font: Optional[Font] = None, position: Optional[Vec3] = None, transform: Optional[Mat4] = None, varyings: Optional["Varyings"] = None, visible: Optional[TYPE_BOOLEAN] = None, discarded: Optional[TYPE_BOOLEAN] = None): ...

    @property
    def type(self) -> Optional[Integer]: ...

    @property
    def position(self) -> Optional[Vec3]: ...

    @property
    def transform(self) -> Optional[Mat4]: ...


class GlyphMaker:
    def __init__(self, font: Optional[Font] = None): ...
    def with_color(self, color: TYPE_VEC4) -> Self: ...
    def with_spans(self, spans: dict[str, "GlyphMaker"]) -> Self: ...
    def with_transform(self, transform: Mat4) -> Self: ...
    def with_varyings(self, varyings: "Varyings") -> Self: ...
    def with_font(self, font: Font) -> Self: ...


class Text:
    def __init__(self, render_layer: RenderLayer, text: String | str | None = None, position: Optional[TYPE_VEC3] = None, layout_param: Optional["LayoutParam"] = None, scale: Optional[TYPE_VEC2] = None, glyph_maker: Any = None,
                 letter_spacing: float = 0, line_height: "LayoutLength" = 0, line_indent: float = 0): ...

    @property
    def text(self) -> str: ...

    @text.setter
    def text(self, text: str): ...

    @property
    def size(self) -> Size: ...

    @property
    def contents(self) -> list[RenderObject]: ...

    @property
    def position(self) -> Vec3: ...

    @position.setter
    def position(self, position): ...

    @property
    def boundaries(self) -> Optional[Boundaries]: ...

    @boundaries.setter
    def boundaries(self, boundaries: Optional[Boundaries]): ...

    @property
    def scale(self) -> Optional[Vec2]: ...

    @scale.setter
    def scale(self, scale: Optional[Vec2]): ...

    def show(self, discarded: Optional[TYPE_BOOLEAN] = None, render_layer: Optional[RenderLayer] = None): ...
    def discard(self): ...


class StringBundle:
    def get_string(self, resid: str) -> str: ...
    def get_string_array(self, resid: str) -> list[str]: ...


class Varyings:
    def __init__(self, **kwargs): ...
    def __setattr__(self, key: str, value): ...
    def __getattr__(self, key: str) -> Any: ...
    def __getitem__(self, subkey: str) -> 'Varyings': ...


class Visibility(Boolean):
    def __init__(self, visible: TYPE_BOOLEAN = True): ...
    def show(self): ...
    def hide(self): ...
    def reset(self, visible: TYPE_BOOLEAN): ...


class Platform:
    @staticmethod
    def get_user_storage_path(p: str) -> str: ...

    @staticmethod
    def get_external_storage_path(p: str) -> str: ...

    @staticmethod
    def sys_call(cmd_id: int, cmd_value: str): ...


class Shape:
    TYPE_NONE = 0
    TYPE_AABB = -1
    TYPE_BALL = -2
    TYPE_BOX = -3
    TYPE_CAPSULE = -4

    def __init__(self, type: TYPE_NAMED_HASH, size: Optional[TYPE_VEC3] = None, origin: Optional[TYPE_VEC3] = None): ...

    @property
    def type(self) -> NamedHash: ...

    @property
    def scale(self) -> tuple[float, float, float]: ...

    @property
    def origin(self) -> tuple[float, float, float]: ...


class RigidbodyController:
    @property
    def active(self) -> bool: ...

    @active.setter
    def active(self, active: bool): ...

    @property
    def position(self) -> TYPE_FLOAT3: ...

    @position.setter
    def position(self, position: TYPE_FLOAT3): ...

    @property
    def linear_velocity(self) -> TYPE_FLOAT3: ...

    @linear_velocity.setter
    def linear_velocity(self, linear_velocity: TYPE_FLOAT3): ...

    @property
    def central_force(self) -> TYPE_FLOAT3: ...

    @central_force.setter
    def central_force(self, central_force: TYPE_FLOAT3): ...

    @property
    def linear_factor(self) -> TYPE_FLOAT3: ...

    @linear_factor.setter
    def linear_factor(self, linear_factor: TYPE_FLOAT3): ...

    @property
    def angular_velocity(self) -> TYPE_FLOAT3: ...

    @angular_velocity.setter
    def angular_velocity(self, angular_velocity: TYPE_FLOAT3): ...

    @property
    def angular_factor(self) -> TYPE_FLOAT3: ...

    @angular_factor.setter
    def angular_factor(self, angular_factor: TYPE_FLOAT3): ...

    @property
    def friction(self) -> float: ...

    @friction.setter
    def friction(self, friction: float): ...

    @property
    def mass(self) -> float: ...

    @mass.setter
    def mass(self, mass: float): ...

    def apply_linear_velocity(self, linear_velocity: TYPE_VEC3, future: Optional[Future] = None) -> Future: ...
    def apply_central_force(self, force: TYPE_VEC3, future: Optional[Future] = None) -> Future: ...
    def apply_central_impulse(self, impulse: TYPE_FLOAT3): ...


class Rigidbody:
    BODY_TYPE_NONE = 0
    BODY_TYPE_KINEMATIC = 1
    BODY_TYPE_DYNAMIC = 2
    BODY_TYPE_STATIC = 3
    BODY_TYPE_RIGID = 3
    BODY_TYPE_SENSOR = 1 << 2
    BODY_TYPE_GHOST = 2 << 2

    @property
    def id(self) -> int: ...

    @property
    def type(self) -> int: ...

    @property
    def shape(self) -> Shape: ...

    @property
    def xy(self) -> tuple: ...

    @property
    def xyz(self) -> tuple: ...

    @property
    def position(self) -> Vec3: ...

    @property
    def rotation(self) -> Optional[Vec4]: ...

    @property
    def width(self) -> float: ...

    @property
    def height(self) -> float: ...

    @property
    def discarded(self) -> Optional[Boolean]: ...

    @property
    def collision_callback(self): ...

    @collision_callback.setter
    def collision_callback(self, collision_callback: "CollisionCallback"): ...

    @property
    def collision_filter(self) -> Optional['CollisionFilter']: ...

    @collision_filter.setter
    def collision_filter(self, collision_filter: Optional['CollisionFilter']): ...

    @property
    def render_object(self) -> RenderObject: ...

    @property
    def tag(self): ...

    @tag.setter
    def tag(self, tag): ...

    @property
    def controller(self) -> RigidbodyController: ...

    def discard(self): ...


class SurfaceController:
    def add_renderer(self, renderer: Renderer, discarded: Optional[Boolean] = None, priority: int = Renderer.PRIORITY_DEFAULT): ...


class CollisionFilter:
    def __init__(self, category_bits: int = 1, mask_bits: int = 0xffffffff, group_index: int = 0): ...

    @property
    def category_bits(self) -> int: ...

    @property
    def mask_bits(self) -> int: ...

    @property
    def group_index(self) -> int: ...


class CollisionManifold:
    @property
    def contact_point(self) -> Tuple[float, float, float]: ...

    @property
    def normal(self) -> Tuple[float, float, float]: ...


class RayCastManifold:
    @property
    def distance(self) -> float: ...

    @property
    def normal(self) -> Tuple[float, float, float]: ...

    @property
    def rigidbody(self) -> Optional[Rigidbody]: ...


class NarrowPhrase: ...


class Constraint:
    def discard(self): ...


class Collider:
    def create_body(self, body_type: int | Integer, shape: Optional[Shape] = None, position: Optional[TYPE_VEC3] = None, rotation: Optional[TYPE_VEC4] = None, collision_filter: Optional[CollisionFilter] = None, discarded: Optional[Boolean] = None) -> Rigidbody: ...
    def create_shape(self, shape_id: TYPE_NAMED_HASH, scale: Optional[TYPE_VEC3] = None, origin: Optional[TYPE_VEC3] = None) -> Shape: ...
    def ray_cast(self, ray_from, ray_to, collision_filter: Optional[CollisionFilter] = None) -> list[RayCastManifold]: ...
    def create_fixed_constraint(self, rigidbody_a: Rigidbody, rigidbody_b: Rigidbody) -> Constraint: ...


class State:
    LINK_TYPE_SUPPORT = 0
    LINK_TYPE_PROPAGATE = 1
    LINK_TYPE_TRANSIT = 2

    def __init__(self, on_activate: Optional[Runnable] = None, on_deactivate: Optional[Runnable] = None): ...

    @property
    def active(self) -> Boolean: ...

    @property
    def suppressed(self) -> Boolean: ...

    def activate(self): ...
    def deactivate(self): ...
    def create_link(self, link_type: int, next_state: "State", mask: int = 0): ...


class LayoutLength:
    LENGTH_TYPE_AUTO = 0
    LENGTH_TYPE_PIXEL = 1
    LENGTH_TYPE_PERCENTAGE = 2

    def __init__(self, value: TYPE_NUMERIC | str, type: int = LENGTH_TYPE_AUTO): ...
    def value(self) -> TYPE_NUMERIC: ...
    def type(self) -> int: ...


class LayoutParam:
    DISPLAY_BLOCK = 0
    DISPLAY_FLOAT = 1
    DISPLAY_ABSOLUTE = 2

    JUSTIFY_CONTENT_FLEX_START = 0
    JUSTIFY_CONTENT_FLEX_END = 1
    JUSTIFY_CONTENT_CENTER = 2
    JUSTIFY_CONTENT_SPACE_BETWEEN = 3
    JUSTIFY_CONTENT_SPACE_AROUND = 4
    JUSTIFY_CONTENT_SPACE_EVENLY = 5

    ALIGN_AUTO = 0
    ALIGN_FLEX_START = 1
    ALIGN_CENTER = 2
    ALIGN_FLEX_END = 3
    ALIGN_STRETCH = 4
    ALIGN_BASELINE = 5
    ALIGN_SPACE_BETWEEN = 6
    ALIGN_SPACE_AROUND = 7

    FLEX_DIRECTION_COLUMN = 0
    FLEX_DIRECTION_COLUMN_REVERSE = 1
    FLEX_DIRECTION_ROW = 2
    FLEX_DIRECTION_ROW_REVERSE = 3

    FLEX_WRAP_NOWRAP = 0
    FLEX_WRAP_WRAP = 1
    FLEX_WRAP_WRAP_REVERSE = 2

    def __init__(self, width: LayoutLength = None, height: LayoutLength = None, layout=None, flex_direction: int = FLEX_DIRECTION_ROW, flex_wrap: int = FLEX_WRAP_NOWRAP, justify_content: int = JUSTIFY_CONTENT_FLEX_START, align_items: int = ALIGN_STRETCH,
                 align_self: int = ALIGN_AUTO, align_content: int = ALIGN_STRETCH, flex_grow: float = 0, flex_basis: LayoutLength = None, margins: Optional[TYPE_VEC4] = None, paddings: Optional[TYPE_VEC4] = None, offset: Optional[TYPE_VEC3] = None): ...


class View:
    def __init__(self, layout_param: LayoutParam, name: str = '', discarded: Optional[Boolean] = None): ...

    @property
    def discarded(self) -> Boolean: ...

    @discarded.setter
    def discarded(self, discarded: Boolean): ...

    @property
    def layout_param(self) -> LayoutParam: ...

    @property
    def layout_position(self) -> Vec3: ...

    @property
    def layout_size(self) -> Size: ...

    @property
    def parent(self) -> Optional[Self]: ...

    @parent.setter
    def parent(self, parent: Self | None): ...

    @property
    def children(self) -> list["View"]: ...

    def add_view(self, view: Self): ...
    def find_view(self, name: str) -> Optional[Self]: ...
    def make_boundaries(self) -> Boundaries: ...


class Graph:
    def __init__(self): ...

    @property
    def nodes(self) -> set['GraphNode']: ...

    def make_node(self, position: Vec3, tag: Any = None) -> 'GraphNode': ...


class GraphNode:
    @property
    def position(self) -> tuple[float, float, float]: ...

    @property
    def tag(self) -> Any: ...

    @tag.setter
    def tag(self, tag: Any): ...

    def add_route(self, to_node: 'GraphNode', length: float): ...


class ConvexHullResolver:
    def __init__(self, check_error: bool = True): ...
    def resolve(self, points: Optional[list[tuple[float, float]]]) -> list[tuple[float, float]]: ...


class PrimitiveModelFactory:
    def __init__(self, mat4: Optional[Mat4] = None): ...
    def make_triangle(self, tex_coordinate: Optional[tuple[float, float, float, float]] = None) -> Model: ...
    def make_plane(self, cols: int, rows: int, tex_coordinate: Optional[tuple[float, float, float, float]] = None) -> Model: ...


class Entity:
    def __init__(self, *components): ...

    @property
    def id(self) -> int: ...

    @property
    def ref(self) -> Ref: ...

    @property
    def discarded(self) -> Discarded: ...

    @property
    def components(self) -> list[Any]: ...

    @property
    def tag(self) -> Any: ...

    def add_components(self, components: Sequence[Any]): ...
    def get_component_list(self, ctype: type[T]) -> list[T]: ...
    def discard(self): ...
    def __getitem__(self, key: type[T]) -> Optional[T]: ...
    def __setitem__(self, key: type[T], value: Any): ...


class CollisionCallback:
    def on_begin_contact(self, rigidbody: Rigidbody, collision_manifold: CollisionManifold): ...
    def on_end_contact(self, rigidbody: Rigidbody): ...


class ApplicationEventListener:
    def on_create(self): ...
    def on_pause(self): ...
    def on_resume(self): ...
    def on_unhandled_event(self, event: Event) -> bool: ...


class PathFinder:
    def __init__(self, searching_node_provider: SearchingNodeProvider): ...
    def find_path(self, start_id: TYPE_INT3, start_position: TYPE_FLOAT3, end_id: TYPE_INT3, end_position: TYPE_FLOAT3, distance_tolerance: float) -> list[TYPE_FLOAT3]: ...


class FPSCounter(String):
    def __init__(self, message_format: str = '.1f% FPS', refresh_interval: float = 2.0): ...


def __trace__(): ...
