from typing import Optional

from ark import FloatArray, Future


class Generator:
    NOISE_TYPE_CELLULAR = 0
    NOISE_TYPE_SIMPLEX = 1
    NOISE_TYPE_PERLIN = 2

    CELLULAR_RETURN_TYPE_INDEX0 = 0
    CELLULAR_RETURN_TYPE_INDEX0_ADD1 = 1
    CELLULAR_RETURN_TYPE_INDEX0_SUB1 = 2
    CELLULAR_RETURN_TYPE_INDEX0_MUL1 = 3
    CELLULAR_RETURN_TYPE_INDEX0_DIV1 = 4

    CELLULAR_DISTANCE_FUNCTION_EUCLIDEAN = 0
    CELLULAR_DISTANCE_FUNCTION_EUCLIDEAN_SQUARED = 1
    CELLULAR_DISTANCE_FUNCTION_MANHATTAN = 2
    CELLULAR_DISTANCE_FUNCTION_HYBRID = 3
    CELLULAR_DISTANCE_FUNCTION_MAX_AXIS = 4
    CELLULAR_DISTANCE_FUNCTION_MINKOWSKI = 5

    def __init__(self, noise_type: int = NOISE_TYPE_SIMPLEX, seed: int = 0): ...

    @property
    def seed(self) -> int: ...

    @seed.setter
    def seed(self, seed: int): ...

    @property
    def scale(self) -> float: ...

    @scale.setter
    def scale(self, frequency: float): ...

    @property
    def use_fractal(self) -> bool: ...

    @use_fractal.setter
    def use_fractal(self, use_fractal: bool): ...

    def set_fractal_octaves(self, octaves: int): ...
    def set_fractal_gain(self, gain: float): ...
    def set_fractal_lacunarity(self, lacunarity: float): ...
    def set_fractal_weighted_strength(self, weighted_strength: float): ...
    def set_cellular_return_type(self, return_type: int): ...
    def set_cellular_distance_function(self, distance_function: int): ...
    def set_grid_jitter(self, jitter: float): ...
    def noise_2d(self, x: float, y: float) -> float: ...
    def noise_3d(self, x: float, y: float, z: float) -> float: ...
    def noise_map_2d(self, bounds: tuple[int, int, int, int], future: Optional[Future] = None) -> FloatArray: ...
