
list(APPEND ARK_PYTHON_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/Python/PC)

set(CMAKE_SHARED_LINKER_FLAGS "/NODEFAULTLIB:python36_d.lib /NODEFAULTLIB:python36.lib /NODEFAULTLIB:python3.lib")
