function(ark_gen_string_table STRING_TABLE_UNIT_NAME NAMESPACES)
set(LOCAL_FILE_NAME ${STRING_TABLE_UNIT_NAME}_string_table)
set(LOCAL_STRING_TABLE_H ${ARK_GENERATED_FILE_DIRECTORY}/${LOCAL_FILE_NAME}.h)
set(LOCAL_STRING_TABLE_CPP ${ARK_GENERATED_FILE_DIRECTORY}/${LOCAL_FILE_NAME}.cpp)
foreach(i IN LISTS ARGN)
file(GLOB LOCAL_FILES "${i}/*")
list(APPEND FILE_DEPENDS ${LOCAL_FILES})
endforeach()
add_custom_command(OUTPUT ${LOCAL_STRING_TABLE_H} ${LOCAL_STRING_TABLE_CPP}
    COMMAND python ${ARK_SRC_DIR}/tools/python/gen_string_table.py -o ${ARK_GENERATED_FILE_DIRECTORY} -n ${STRING_TABLE_UNIT_NAME} -p ${NAMESPACES} ${ARGN}
    DEPENDS ${ARK_SRC_DIR}/tools/python/gen_string_table.py ${FILE_DEPENDS}
    WORKING_DIRECTORY ${PROJECT_SOURCE_DIR})
list(APPEND LOCAL_GENERATED_SRC_LIST ${LOCAL_STRING_TABLE_H} ${LOCAL_STRING_TABLE_CPP})
set(LOCAL_GENERATED_SRC_LIST ${LOCAL_GENERATED_SRC_LIST} PARENT_SCOPE)

list(APPEND LOCAL_BOOTSTRAP_FUNCS "__ark_bootstrap_${LOCAL_FILE_NAME}__")
set(LOCAL_BOOTSTRAP_FUNCS ${LOCAL_BOOTSTRAP_FUNCS} PARENT_SCOPE)

endfunction(ark_gen_string_table)
